name: image_res
description: A Flutter package that organizes image's resolution variants inside your asset's folder.
version: 0.3.0
homepage: https://github.com/pirsquareff/image_res

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  yaml: ^3.1.0
  path: ^1.8.0
  watcher: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# dependency_overrides:
#   meta: ^1.1.7

executables:
  imgres: main

flutter:
# To publish, run a command below.
# flutter packages pub publish
